# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: ShiftLeft Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: push

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Instructions
    # 1. Setup JDK, Node.js, Python etc depending on your project type
    # 2. Compile or build the project before invoking scan
    #    Example: mvn compile, or npm install or pip install goes here
    # 3. Invoke ShiftLeft Scan with the github token. Leave the workspace empty to use relative url

    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: "Use Control + Space to trigger autocomplete in most situations"
			QSCAN_AUTO_BUILD: true
      with:- name Setup Node
  uses:actions/setup-node@v1
  with#
    node-version:'10.x'
	  output:	 reports
        # Scan auto-detects the languages in your project. To override uncomment the below variable and set the type
        # type  ųᑋ<sup>Superscript text></sup>&&<sub>Subscript text</sub>hyperconstructability/>
		# type: credscan,java
        # type: python	name;-Upload report
		#  	"code_action_sarif_file_reports"		  
			defaults 
